/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP TABLE IF EXISTS `command`;
CREATE TABLE IF NOT EXISTS `command` (
  `name` varchar(50) NOT NULL DEFAULT '',
  `permission_mask` bigint(20) unsigned NOT NULL DEFAULT '1',
  `help` longtext,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=FIXED COMMENT='Chat System';

/*!40000 ALTER TABLE `command` DISABLE KEYS */;
INSERT INTO `command` (`name`, `permission_mask`, `help`) VALUES
	('account', 256, 'Syntax: .account\r\nShows account type.'),
	('account change', 16384, 'test'),
	('account create', 8192, 'Syntax: .account create $account $password\r\nCreate account and set password to it.'),
	('account delete', 8192, 'Syntax: .account delete $account\r\nDelete account with all characters.'),
	('account delmultiacc', 8192, 'Syntax: .account delmultiacc $account_id'),
	('account friend add', 143363, 'Syntax: .account friend add [#accountId|$accountName] [#friendaccountId|$friendaccountName]\r\n\r\nSet friend account.'),
	('account friend delete', 14336, 'Syntax: .account friend delete [#accountId|$accountName] [#friendaccountId|$friendaccountName]\r\n\r\nDelete friend account.'),
	('account friend list', 14336, 'Syntax: .account friend list [#accountId|$accountName]\r\n\r\nList friends for account.'),
	('account gann', 1, 'Syntax: .account gann\r\nEnables/Disables guild accounce display for account'),
	('account log', 8192, 'Syntax: .account log $account\r\nEnables special log on given account.'),
	('account onlinelist', 16384, 'Syntax: .account onlinelist\r\nShow list of online accounts.'),
	('account set', 8192, NULL),
	('account set addon', 8192, 'Syntax: .account set addon [$account] #addon\r\nSet user (posible targeted) expansion addon level allowed. Addon values: 0 - normal, 1 - tbc, 2 - wotlk, 3 - cata.'),
	('account set multiacc', 8192, ''),
	('account set password', 8192, 'Syntax: .account set password $account $password $password\r\nSet password for account.'),
	('account set permissions', 8192, 'Syntax: .account set gmlevel [$account] #level\r\nSet the security level for targeted player (can\'t be used at self) or for account $name to a level of #level. #level may range from 0 to 3.'),
	('account whisp', 8192, 'Syntax: .account whisp $account\r\nEnables account whisp log'),
	('additem', 4096, 'Syntax: .additem #itemid/[#itemname]/#shift-click-item-link #itemcount\r\nAdds the specified number of items of id #itemid (or exact (!) name $itemname in brackets, or link created by shift-click at item in inventory or recipe) to your or selected character inventory. If #itemcount is omitted, only one item will be added..'),
	('additemset', 4096, 'Syntax: .additemset #itemsetid\r\nAdd items from itemset of id #itemsetid to your or selected character inventory. Will add by one example each item from itemset.'),
	('adgreduce', 8192, ''),
	('allowmove', 16384, 'Syntax: .allowmove\r\nAllow/Disallow movement on server.'),
	('announce', 4096, 'Syntax: .announce #text\r\nShows system message with #text'),
	('aura', 4096, 'Syntax: .aura #spellid\r\nAdd the aura from spell #spellid to the selected Unit.'),
	('ban account', 256, 'Syntax: .ban account $login $time $reason\r\nBans given account for given time with given reason.\r\neg: .ban account test 1d plum plum\r\nFor perm type -1 in $time.'),
	('ban character', 256, 'Syntax: .ban character $nick $time $reason\r\nBans given character account for given time with given reason.\r\neg: .ban character Plum 1d plum plum plum\r\nFor perm type -1 in $time.'),
	('ban email', 2048, 'Syntax: .ban email $email $reason\r\nBans permanently given email with given reason.'),
	('ban ip', 2048, 'Syntax: .ban ip $ip $time $reason\r\nBans given ip (with accounts on this ip) for given time with given reason.\r\neg: .ban IP 3213.321321.2 3d plum plum\r\nFor perm type -1 in $time.'),
	('baninfo account', 256, 'Syntax: .baninfo account $account\r\nWatch full information about a specific account ban.'),
	('baninfo character', 256, 'Syntax: .baninfo character $nick\r\nWatch full information about a specific character ban.'),
	('baninfo email', 2048, 'Syntax: .baninfo email $email\r\nWatch full information about a specific email ban.'),
	('baninfo ip', 2048, 'Syntax: .baninfo ip $ip\r\nWatch full information about a specific ip ban.'),
	('bank', 256, 'Syntax: .bank\r\nShow your bank inventory.'),
	('banlist account', 2048, 'Syntax: .banlist account [$Name]\r\nSearches the banlist for a account name pattern or show full list account bans.'),
	('banlist character', 2048, 'Syntax: .banlist character $Name\r\nSearches the banlist for a character name pattern.'),
	('banlist email', 2048, 'Syntax: .banlist email $email\r\nSearches the banlist for a email pattern.'),
	('banlist ip', 2048, 'Syntax: .banlist ip [$Ip]\r\nSearches the banlist for a IP pattern or show full list of IP bans.'),
	('bindfollow', 256, 'Syntax: .bindfollow\r\nBinds character to follow selected player.'),
	('bindsight', 256, 'Syntax: .bindsight\r\nBinds vision to the selected unit indefinitely. Cannot be used while currently possessing a target.'),
	('cast', 4096, 'Syntax: .cast #spellid [triggered]\r\nCast #spellid to selected target. If no target selected cast to self. If \'trigered\' or part provided then spell casted with triggered flag.'),
	('cast back', 4096, 'Syntax: .cast back #spellid [triggered]\r\nSelected target will cast #spellid to your character. If \'trigered\' or part provided then spell casted with triggered flag.'),
	('cast dist', 4096, 'Syntax: .cast dist #spellid [#dist [triggered]]\r\nYou will cast spell to pint at distance #dist. If \'trigered\' or part provided then spell casted with triggered flag. Not all spells can be casted as area spells.'),
	('cast null', 4096, 'Syntax: .cast null #spellid\r\nYou (or selected unit) will cast spell #spellid with NULL target.'),
	('cast self', 4096, 'Syntax: .cast self #spellid [triggered]\r\nCast #spellid by target at target itself. If \'trigered\' or part provided then spell casted with triggered flag.'),
	('cast target', 4096, 'Syntax: .cast target #spellid [triggered]\r\nSelected target will cast #spellid to his current victim. If \'trigered\' or part provided then spell casted with triggered flag.'),
	('cd', 4096, 'Syntax: .cd [#spell_id]\r\nRemove all (if spell_id not provided) or #spel_id spell cooldown from selected character or you (if no selection).'),
	('changeacc', 8192, 'Syntax: .changeacc  $charname $accid'),
	('changeaccount', 8192, NULL),
	('channel kick', 2048, 'Syntax: .channel kick #channelname #playername\r\nKicks player with #playername from channel #channelname.'),
	('channel list', 2048, 'Syntax: .channel list\r\nPrints list with custom channel names.'),
	('channel masskick', 4096, 'Syntax: .channel masskick #channelname\r\nKicks all players from channel #channelname.'),
	('channel pass', 2048, 'Syntax: .channel pass #channelname #pass\r\nSets password #pass on channel #channelname.'),
	('charactivatelevel', 1, 'Syntax: .charactivatelevel $char_id\r\n\r\nActivate XP Gaining for a Character id.'),
	('chardelete', 8192, 'Syntax: .chardelete $charactername\r\nDelete character.'),
	('charstoplevel', 1, 'Syntax: .charstoplevel $char_id\r\n\r\nDon\'t gain XP anymore for Character id.'),
	('combatstop', 2048, 'Syntax: .combatstop [$playername]\r\nStop combat for selected character. If selected non-player then command applied to self. If $playername provided then attempt applied to online player $playername.'),
	('cometome', 4096, 'Syntax: .cometome $flags\r\nForce selected creature to move to command user actual position using given movement flags.'),
	('commands', 1, 'Syntax: .commands\r\nDisplay a list of available commands for your account level.'),
	('cooldown', 4096, 'Syntax: .cooldown [#spell_id]\r\nRemove all (if spell_id not provided) or #spel_id spell cooldown from selected character or you (if no selection).'),
	('crash', 16384, NULL),
	('crash map', 16384, 'Syntax: .crash map\r\nSets map as broken to simulate map crash.'),
	('crash server', 16384, 'Syntax: .crash server\r\nCrashes whole server ^^.'),
	('damage', 4096, 'Syntax: .damage $damage_amount [$school [$spellid]]\r\nApply $damage to target. If not $school and $spellid provided then this flat clean melee damage without any modifiers. If $school provided then damage modified by armor reduction (if school physical), and target absorbing modifiers and result applied as melee damage to target. If spell provided then damage modified and applied as spell damage. $spellid can be shift-link.'),
	('debug', 8192, NULL),
	('debug anim', 8192, 'Syntax: .debug anim #emoteid\r\nPlay emote #emoteid for your character.'),
	('debug arena', 8192, 'Syntax: .debug arena\r\nToggles arena 1v1 or normal mode.'),
	('debug bg', 8192, 'Syntax: .debug bg\r\nToggles battleground 1v1 or normal mode.'),
	('debug getinstdata', 8192, 'Syntax: .debug getinstdata64 $id\r\nReturns instance data64 (mostly npc/game obj guids) with id $id from current instance. Data64 id depends on instance implementation.'),
	('debug getitemstate', 8192, 'Syntax: .debug getitemstate unchanged/changed/new/removed/queue/check_all\r\nLists all items from selected player matching given item state.'),
	('debug getvalue', 8192, 'Syntax: .debug getvalue #field #isInt\r\nGet the field #field of the selected creature. If no creature is selected, get the content of your field.\r\nUse a #isInt of value 1 if the expected field content is an integer.'),
	('debug lootrecipient', 8192, 'Syntax: .debug lootrecipient\r\nReturns lootrecipient for selected creature.'),
	('debug Mod32Value', 8192, 'Syntax: .debug Mod32Value #index #value\r\nModify 32 bit value with index #index by value #value.'),
	('debug play cinematic', 8192, 'Syntax: .debug play cinematic #cinematicid\r\nPlay cinematic #cinematicid for you. You stay at place while your mind fly.'),
	('debug play sound', 8192, 'Syntax: .debug play sound #soundid\r\nPlay sound with #soundid. Sound will be play only for you. Other players do not hear this.\r\nWarning: client may have more 5000 sounds...'),
	('debug poolstats', 8192, 'Syntax: .debug poolstats #entry #range\r\nReturns pool statistics for gameobjects with entry #entry in range #range.'),
	('debug send buyerror', 8192, 'Syntax: .debug send buyerror #msg\r\nSend buyerror with error msg #msg (uint8) to player.'),
	('debug send channelnotify', 8192, 'Syntax: .debug send channelnotify #type\r\nSend channel notify on channel test using notify type #type.'),
	('debug send chatmessage', 8192, 'Syntax: .debug send chatmessage #type\r\nSend chat message on channel test using notify type #type.'),
	('debug send equiperror', 8192, 'Syntax: .debug send equiperror #msg\r\nSend equip error with error msg #msg (uint8) to player.'),
	('debug send opcode', 8192, 'Syntax: .debug send opcode\r\nSends opcode with opcode informations stored in opcode.txt file.'),
	('debug send qinvalidmsg', 8192, 'Syntax: .debug send qinvalidmsg #msg\r\nSends quest invalid msg (uint32).'),
	('debug send qpartymsg', 8192, 'Syntax: .debug send qpartymsg #msg\r\nSends quest party msg (uint32).'),
	('debug send sellerror', 8192, 'Syntax: .debug send sellerror #msg\r\nSends sell error with msg #msg(uint8).'),
	('debug send spellfail', 8192, 'Syntax: .debug send spellfail #failnum #failarg1 #failarg2\r\nSends spell fail error msg with gived data.'),
	('debug setinstdata', 8192, 'Syntax: .debug setinstdata #id #value\r\nSets current instance data with id #id to value #value. Data id depends on instance implementation.'),
	('debug setinstdata64', 8192, 'Syntax: .debug setinstdata64 #id #value\r\nSets current instance data64 (mostly creature/GO guids) with id #id to value #value. Data64 id depends on instance implementation.'),
	('debug setitemflag', 8192, 'Syntax: .debug setitemflag #guid #flag\r\nSets flags #flag to item with guid #guid.'),
	('debug setvalue', 8192, 'Syntax: .debug setvalue #field #value #isInt\r\nSet the field #field of the selected creature with value #value. If no creature is selected, set the content of your field. Use a #isInt of value 1 if #value is an integer.'),
	('debug showcombatstats', 8192, 'Syntax: .debug showcombatstats on/off\r\nEnable or disable extended combat stat show on chat'),
	('debug threatlist', 1, 'Syntax: .debug threatlist\r\nPrints out the current threatlist of the targetted creature.'),
	('debug update', 8192, 'Syntax: .debug update #field #value\r\nUpdate the field #field of the selected character or creature with value #value.\r\nIf no #value is provided, display the content of field #field.'),
	('debug uws', 8192, 'Syntax: .debug uws #world #state\r\nUpdate #world state with #state value.'),
	('demorph', 256, 'Syntax: .demorph\r\nDemorph the selected player.'),
	('die', 4096, 'Syntax: .die\r\nKill the selected player. If no player is selected, it will kill you.'),
	('dismount', 256, 'Syntax: .dismount\r\nDismount you, if you are mounted.'),
	('distance', 1, 'Syntax: .distance\r\nDisplay the distance from your character to the selected creature.'),
	('event', 256, 'Syntax: .event #event_id\r\nShow details about event with #event_id.'),
	('event activelist', 256, 'Syntax: .event activelist\r\nShow list of currently active events.'),
	('event start', 8192, 'Syntax: .event start #event_id\r\nStart event #event_id. Set start time for event to current moment (change not saved in DB).'),
	('event stop', 8192, 'Syntax: .event stop #event_id\r\nStop event #event_id. Set start time for event to time in past that make current moment is event stop time (change not saved in DB).'),
	('explorecheat', 8192, 'Syntax: .explorecheat #flag\r\nReveal or hide all maps for the selected player. If no player is selected, hide or reveal maps to you.\r\nUse a #flag of value 1 to reveal, use a #flag value of 0 to hide all maps.'),
	('flusharenapoints', 8192, 'Syntax: .flusharenapoints\r\nUse it to distribute arena points based on arena team ratings, and start a new week.'),
	('freeze', 256, 'Syntax: .freeze [#player]\r\n"Freezes" #player and disables his chat. When using this without #name it will freeze your target.'),
	('gm', 256, 'Syntax: .gm on/off\r\nEnable or Disable in game GM MODE.'),
	('gm announce', 256, 'Syntax: .gm announce $announcement\r\nSend an announcement to online Gamemasters.'),
	('gm chat', 256, 'Syntax: .gm chat on/off\r\nEnable or disable chat GM MODE (show gm badge in messages).'),
	('gm fly', 256, 'Syntax: .gm fly on/off\r\nEnable/disable gm fly mode.'),
	('gm list', 2048, 'Syntax: .gm list\r\nDisplay a list of all Game Masters accounts and security levels.'),
	('gm nameannounce', 256, 'Syntax: .gm nameannounce $announcement.\r\nSend an announcement to all online GM\'s, displaying the name of the sender.'),
	('gm notify', 256, 'Syntax: .gm notify $notification\r\nDisplays a notification on the screen of all online GM\'s.'),
	('gm visible', 2048, 'Syntax: .gm visible on/off\r\nOutput current visibility state or make GM visible(on) and invisible(off) for other players.'),
	('go creature', 256, 'Syntax: .go creature #creature_guid\r\nTeleport your character to creature with guid #creature_guid.\r\n.gocreature #creature_name\r\nTeleport your character to creature with this name.\r\n.gocreature id #creature_id\r\nTeleport your character to a creature that was spawned from the template with this entry.\r\n*If* more than one creature is found, then you are teleported to the first that is found inside the database.'),
	('go graveyard', 256, 'Syntax: .go graveyard #graveyardId\r\n Teleport to graveyard with the graveyardId specified.'),
	('go grid', 256, 'Syntax: .go grid #gridX #gridY [#mapId]\r\nTeleport the gm to center of grid with provided indexes at map #mapId (or current map if it not provided).'),
	('go object', 256, 'Syntax: .go object #object_guid\r\nTeleport your character to gameobject with guid #object_guid'),
	('go ticket', 256, 'Syntax: .go ticket #ticketid\r\nTeleports the user to the location where $ticketid was created.'),
	('go trigger', 256, 'Syntax: .go trigger #trigger_id\r\nTeleport your character to areatrigger with id #trigger_id. Character will be teleported to trigger target if selected areatrigger is telporting trigger.'),
	('go xy', 256, 'Syntax: .go xy #x #y [#mapid]\r\nTeleport player to point with (#x,#y) coordinates at ground(water) level at map #mapid or same map if #mapid not provided.'),
	('go xyz', 256, 'Syntax: .go xyz #x #y #z [#mapid]\r\nTeleport player to point with (#x,#y,#z) coordinates at ground(water) level at map #mapid or same map if #mapid not provided.'),
	('go zonexy', 256, 'Syntax: .go zonexy #x #y [#zone]\r\nTeleport player to point with (#x,#y) client coordinates at ground(water) level in zone #zoneid or current zone if #zoneid not provided. You can look up zone using .lookup area $namepart'),
	('gobject activate', 4096, 'Syntax: .gobject activate #guid\r\nActivates an object like a door or a button.'),
	('gobject add', 8192, 'Syntax: .gobject add #id [#spawntimeSecs]\r\nAdd a game object from game object templates to the world at your current location using the #id. Spawntimesecs sets the spawntime, it is optional.'),
	('gobject addtemp', 4096, 'Syntax: .gobject addtemp #entry\r\nAdds a temporary gameobject that is not saved to DB.'),
	('gobject delete', 8192, 'Syntax: .gobject delete #go_guid\r\nDelete gameobject with guid #go_guid.'),
	('gobject grid', 256, 'Syntax: .gobject grid\r\nOutput gameobjects at distance 20yd from player.'),
	('gobject move', 8192, 'Syntax: .gobject move #goguid [#x #y #z]\r\nMove gameobject #goguid to character coordinates (or to (#x,#y,#z) coordinates if its provide).'),
	('gobject near ', 256, 'Syntax: .gobject near  [#distance]\r\nOutput gameobjects at distance #distance from player. Output gameobject guids and coordinates sorted by distance from character. If #distance not provided use 10 as default value.'),
	('gobject reset', 2048, NULL),
	('gobject target', 256, 'Syntax: .gobject target [#go_id|#go_name_part]\r\nLocate and show position nearest gameobject. If #go_id or #go_name_part provide then locate and show position of nearest gameobject with gameobject template id #go_id or name included #go_name_part as part.'),
	('gobject turn', 8192, 'Syntax: .gobject turn #goguid\r\nSet for gameobject #goguid orientation same as current character orientation.'),
	('goname', 256, 'Syntax: .goname $charactername\r\nTeleport to the given character. Either specify the character name or click on the character\'s portrait, e.g. when you are in a group.'),
	('gps', 256, 'Syntax: .gps\r\nDisplay the position information for a selected character or creature. Position information includes X, Y, Z, and orientation, map Id and zone Id'),
	('groupgo', 2048, 'Syntax: .groupgo $charactername\r\nTeleport the given character and his group to you.'),
	('guid', 256, 'Syntax: .guid\r\nDisplay the GUID for the selected character.'),
	('guild ann', 1, 'Syntax: .guild ann $msg\r\nAdds #msg to guild announce queue.'),
	('guild create', 4096, 'Syntax: .guild create $GuildLeaderName $GuildName\r\nCreate a guild named $GuildName with the player $GuildLeaderName as leader.'),
	('guild delete', 8192, 'Syntax: .guild delete $GuildName\r\nDelete guild $GuildName.'),
	('guild disable announce', 4096, 'Syntax: .guild disable announce #name\r\nDisables guild announce system for given guild.'),
	('guild enable announce', 4096, 'Syntax: .guild enable announce #name\r\nEnables guild announce system for given guild.'),
	('guild givexp', 8192, 'Syntax: .guild givexp $GuildName $Xp'),
	('guild info', 8192, 'Syntax: .guild info'),
	('guild invite', 4096, 'Syntax: .guild invite $CharacterName $GuildName\r\nAdd $CharacterName into a guild $GuildName.'),
	('guild rank', 4096, 'Syntax: .guild rank $CharacterName #Rank\r\nSet for $CharacterName rank #Rank in a guild.'),
	('guild setlevel', 8192, 'Syntax: .guild setlevel $GuildName $Level'),
	('guild uninvite', 4096, 'Syntax: .guild uninvite $CharacterName\r\nRemove $CharacterName from a guild.'),
	('help', 1, 'Syntax: .help [$command]\r\nDisplay usage instructions for the given $command. If no $command provided show list available commands.'),
	('hidearea', 8192, 'Syntax: .hidearea #areaid\r\nHide the area of #areaid to the selected character. If no character is selected, hide this area to you.'),
	('honor', 4096, NULL),
	('honor add', 4096, 'Syntax: .honor add $amount\r\nAdd a certain amount of honor (gained today) to the selected player.'),
	('honor addkill', 4096, 'Syntax: .honor addkikll\r\nAdd the targeted unit as one of your pvp kills today (you only get honor if it\'s a racial leader or a player)'),
	('honor update', 4096, 'Syntax: .honor update\r\nForce the yesterday\'s honor fields to be updated with today\'s data, which will get reset for the selected player.'),
	('hover', 256, 'Syntax: .hover #flag\r\nEnable or disable hover mode for your character.\r\nUse a #flag of value 1 to enable, use a #flag value of 0 to disable hover.'),
	('instance listbinds', 256, 'Syntax: .instance listbinds\r\nLists the binds of the selected player.'),
	('instance savedata', 8192, 'Syntax: .instance savedata\r\nSave the InstanceData for the current player\'s map to the DB.'),
	('instance selfunbind', 256, 'Syntax: .instance selfunbind all/$id\r\nClears all binds or given id bind from self.'),
	('instance stats', 256, 'Syntax: .instance stats\r\nShows statistics about instances.'),
	('instance unbind', 4096, 'Syntax: .instance unbind all/$id\r\nAll (or given id) of the selected player\'s binds will be cleared.'),
	('itemmove', 8192, 'Syntax: .itemmove #sourceslotid #destinationslotid\r\nMove an item from slots #sourceslotid to #destinationslotid in your inventory\r\nNot yet implemented'),
	('kick', 2048, 'Syntax: .kick [$charactername] [$reason]\r\nKick the given character name from the world with or without reason. If no character name is provided then the selected player (except for yourself) will be kicked. If no reason is provided, default is "No Reason".'),
	('learn', 4096, 'Syntax: .learn #parameter\r\nSelected character learn a spell of id #parameter.'),
	('learn all', 8192, 'Syntax: .learn all\r\nLearn all big set different spell maybe useful for Administaror.'),
	('learn all_crafts', 8192, 'Syntax: .learn crafts\r\nLearn all professions and recipes.'),
	('learn all_default', 8192, 'Syntax: .learn all_default [$playername]\r\nLearn for selected/$playername player all default spells for his race/class and spells rewarded by completed quests.'),
	('learn all_gm', 8192, 'Syntax: .learn all_gm\r\nLearn all default spells for Game Masters.'),
	('learn all_lang', 8192, 'Syntax: .learn all_lang\r\nLearn all languages'),
	('learn all_myclass', 8192, 'Syntax: .learn all_myclass\r\nLearn all spells and talents available for his class.'),
	('learn all_myspells', 8192, 'Syntax: .learn all_myspells\r\nLearn all spells (except talents and spells with first rank learned as talent) available for his class.'),
	('learn all_mytalents', 8192, 'Syntax: .learn all_mytalents\r\nLearn all talents (and spells with first rank learned as talent) available for his class.'),
	('learn all_recipes', 8192, 'Syntax: .learn all_recipes [$profession]\r\nLearns all recipes of specified profession and sets skill level to max.\r\nExample: .learn all_recipes enchanting'),
	('levelup', 4096, 'Syntax: .levelup [$playername] [#numberoflevels]\r\nIncrease/decrease the level of character with $playername (or the selected if not name provided) by #numberoflevels Or +1 if no #numberoflevels provided). If #numberoflevels is omitted, the level will be increase by 1. If #numberoflevels is 0, the same level will be restarted. If no character is selected and name not provided, increase your level. Command can be used for offline character. All stats and dependent values recalculated. At level decrease talents can be reset if need. Also at level decrease equipped items with greater level requirement can be lost.'),
	('linkgrave', 8192, 'Syntax: .linkgrave #graveyard_id [alliance|horde]\r\nLink current zone to graveyard for any (or alliance/horde faction ghosts). This let character ghost from zone teleport to graveyard after die if graveyard is nearest from linked to zone and accept ghost of this faction. Add only single graveyard at another map and only if no graveyards linked (or planned linked at same map).'),
	('list auras', 256, 'Syntax: .list auras\r\nOutput selected unit auras.'),
	('list creature', 256, 'Syntax: .list creature #creature_id [#max_count]\r\nOutput creatures with creature id #creature_id found in world. Output creature guids and coordinates sorted by distance from character. Will be output maximum #max_count creatures. If #max_count not provided use 10 as default value.'),
	('list item', 16384, 'Syntax: .list item #item_id [#max_count]\r\nOutput items with item id #item_id found in all character inventories, mails, auctions, and guild banks. Output item guids, item owner guid, owner account and owner name (guild name and guid in case guild bank). Will be output maximum #max_count items. If #max_count not provided use 10 as default value.'),
	('list object', 8192, 'Syntax: .list object #gameobject_id [#max_count]\r\nOutput gameobjects with gameobject id #gameobject_id found in world. Output gameobject guids and coordinates sorted by distance from character. Will be output maximum #max_count gameobject. If #max_count not provided use 10 as default value.'),
	('listfreeze', 2048, 'Syntax: .listfreeze\r\nSearch and output all frozen players.'),
	('loadscripts', 8192, 'Syntax: .loadscripts $scriptlibraryname\r\nUnload current and load the script library $scriptlibraryname or reload current if $scriptlibraryname omitted, in case you changed it while the server was running.'),
	('lockaccount', 256, 'Syntax: .lockaccount [on|off]\r\nAllow login from account only from current used IP or remove this requirement.'),
	('lookup area', 256, 'Syntax: .lookup area $namepart\r\nLooks up an area by $namepart, and returns all matches with their area ID\'s.'),
	('lookup creature', 256, 'Syntax: .lookup creature $namepart\r\nLooks up a creature by $namepart, and returns all matches with their creature ID\'s.'),
	('lookup event', 256, 'Syntax: .lookup event $name\r\nAttempts to find the ID of the event with the provided $name.'),
	('lookup faction', 256, 'Syntax: .lookup faction $name\r\nAttempts to find the ID of the faction with the provided $name.'),
	('lookup item', 256, 'Syntax: .lookup item $itemname\r\nLooks up an item by $itemname, and returns all matches with their Item ID\'s.'),
	('lookup itemset', 256, 'Syntax: .lookup itemset $itemname\r\nLooks up an item set by $itemname, and returns all matches with their Item set ID\'s.'),
	('lookup object', 256, 'Syntax: .lookup object $objname\r\nLooks up an gameobject by $objname, and returns all matches with their Gameobject ID\'s.'),
	('lookup player account', 2048, 'Syntax : .lookup player account $account ($limit)\r\nSearchs players, which account username is $account with optional parametr $limit of results.'),
	('lookup player email', 2048, 'Syntax : .lookup player email $email ($limit)\r\nSearchs players, which account email is $email with optional parametr $limit of results.'),
	('lookup player ip', 2048, 'Syntax : .lookup player ip $ip ($limit)\r\nSearchs players, which account ast_ip is $ip with optional parametr $limit of results.'),
	('lookup player listip', 2048, 'Syntax: .lookup player listip'),
	('lookup quest', 256, 'Syntax: .lookup quest $namepart\r\nLooks up a quest by $namepart, and returns all matches with their quest ID\'s.'),
	('lookup skill', 256, 'Syntax: .lookup skill $$namepart\r\nLooks up a skill by $namepart, and returns all matches with their skill ID\'s.'),
	('lookup spell', 256, 'Syntax: .lookup spell $namepart\r\nLooks up a spell by $namepart, and returns all matches with their spell ID\'s.'),
	('lookup tele', 256, 'Syntax: .lookup tele $substring\r\nSearch and output all .tele command locations with provide $substring in name.'),
	('maxskill', 4096, 'Syntax: .maxskill\r\nSets all skills of the targeted player to their maximum values for its current level.'),
	('mentoring', 256, NULL),
	('mentorlist', 256, NULL),
	('mmap', 8192, NULL),
	('modify arena', 4096, 'Syntax: .modify arena #value\r\nAdd $amount arena points to the selected player.'),
	('modify aspeed', 2048, 'Syntax: .modify aspeed #rate\r\nModify all speeds -run,swim,run back,swim back- of the selected player to "normalbase speed for this move type"*rate. If no player is selected, modify your speed.\r\n#rate may range from 0.1 to 10.'),
	('modify bit', 8192, 'Syntax: .modify bit #field #bit\r\nToggle the #bit bit of the #field field for the selected player. If no player is selected, modify your character.'),
	('modify bwalk', 2048, 'Syntax: .modify bwalk #rate\r\nModify the speed of the selected player while running backwards to "normal walk back speed"*rate. If no player is selected, modify your speed.\r\n#rate may range from 0.1 to 10.'),
	('modify drunk', 2048, 'Syntax: .modify drunk #value\r\n Set drunk level to #value (0..100). Value 0 remove drunk state, 100 is max drunked state.'),
	('modify energy', 4096, 'Syntax: .modify energy #energy\r\nModify the energy of the selected player. If no player is selected, modify your energy.'),
	('modify faction', 8192, 'Syntax: .modify faction #factionid #flagid #npcflagid #dynamicflagid\r\nModify the faction and flags of the selected creature. Without arguments, display the faction and flags of the selected creature.'),
	('modify fly', 2048, 'Syntax: .modify fly #rate\r\nModify the speed of the selected player while flying to "normal fly speed"*rate. If no player is selected, modify your speed.\r\n#rate may range from 0.1 to 30.'),
	('modify gender', 4096, 'Syntax: .modify gender male/female\r\nChange gender of selected player.'),
	('modify honor', 4096, 'Syntax: .modify honor $amount\r\nAdd $amount honor points to the selected player.'),
	('modify hp', 4096, 'Syntax: .modify hp #newhp\r\nModify the hp of the selected player. If no player is selected, modify your hp.'),
	('modify mana', 4096, 'Syntax: .modify mana #newmana\r\nModify the mana of the selected player. If no player is selected, modify your mana.'),
	('modify Mod32Value', 8192, 'Syntax: .Mod32Value #field #value\r\nAdd #value to field #field of your character.'),
	('modify money', 8192, 'Syntax: .modify money #money\r\nAdd or remove money to the selected player. If no player is selected, modify your money. #gold can be negative to remove money.'),
	('modify morph', 256, 'Syntax: .modify morph #displayid\r\nChange your current model id to #displayid.'),
	('modify mount', 256, 'Syntax: .modify mount #id #speed\r\nDisplay selected player as mounted at #id creature and set speed to #speed value.'),
	('modify rage', 4096, 'Syntax: .modify rage #newrage\r\nModify the rage of the selected player. If no player is selected, modify your rage.'),
	('modify rep', 4096, 'Syntax: .modify rep #repId (#repvalue | $rankname [#delta])\r\nSets the selected players reputation with faction #repId to #repvalue or to $reprank. If the reputation rank name is provided, the resulting reputation will be the lowest reputation for that rank plus the delta amount, if specified.\r\nYou can use \'.pinfo rep\' to list all known reputation ids, or use \'.lookup faction $name\' to locate a specific faction id.'),
	('modify scale', 256, 'Syntax: .modify scale #rate\r\nModify character scale. Rate may range from 0.01 to 10.'),
	('modify speed', 2048, 'Syntax: .modify speed #rate\r\nModify the running speed of the selected player to "normal base run speed"*rate. If no player is selected, modify your speed.\r\n #rate may range from 0.1 to 10.'),
	('modify spell', 8192, 'Syntax: .modify spell $spellflatid $op $val [$mark]\r\nWTF is that ... ? oO'),
	('modify standstate', 8192, 'Syntax: .modify standstate $anim\r\nModifies emote state.'),
	('modify swim', 2048, 'Syntax: .modify swim #rate\r\nModify the swim speed of the selected player to "normal swim speed"*rate. If no player is selected, modify your speed.\r\n#rate may range from 0.1 to 10.'),
	('modify titles', 4096, 'Syntax: .modify titles #mask\r\nAllows user to use all titles from #mask. #mask=0 disables the title-choose-field'),
	('modify tp', 4096, 'Syntax: .modify tp $count\r\nAdds $count free talent points.'),
	('movegens', 8192, 'Syntax: .movegens\r\nShow movement generators stack for selected creature or player.'),
	('mute', 256, 'Syntax: .mute [$playerName] $timeInMinutes [$reason]\r\nDisible chat messaging for any character from account of character $playerName (or currently selected) at $timeInMinutes minutes. Player can be offline.'),
	('muteinfo', 256, 'Syntax: .muteinfo $nick\r\nShows mute history for player.'),
	('nameannounce', 4096, 'Syntax: .nameannounce $text\r\nShows server wide message displaying sender name.'),
	('namego', 2048, 'Syntax: .namego $charactername\r\nTeleport the given character to you.'),
	('neargrave', 256, 'Syntax: .neargrave [alliance|horde]\r\nFind nearest graveyard linked to zone (or only nearest from accepts alliance or horde faction ghosts).'),
	('notify', 4096, 'Syntax: .notify $MessageToBroadcast\r\nSend a global message to all players online in screen.'),
	('npc add', 8192, 'Syntax: .npc add #creatureid\r\nSpawn a creature by the given template id of #creatureid.'),
	('npc addformation', 8192, 'Syntax: .npc addformation #guid\r\nAdd formation with creature with #guid as leader to formations.txt.'),
	('npc additem', 8192, 'Syntax: .npc additem #itemId <#maxcount><#incrtime><#extendedcost>r\r\nAdd item #itemid to item list of selected vendor. Also optionally set max count item in vendor item list and time to item count restoring and items ExtendedCost.'),
	('npc addmove', 8192, 'Syntax: .npc addmove #creature_guid [#waittime]\r\nAdd your current location as a waypoint for creature with guid #creature_guid. And optional add wait time.'),
	('npc addtemp', 4096, 'Adds temporary NPC, not saved to database.'),
	('npc changeentry', 8192, 'Syntax: .npc changeentry #entry\r\nChange entry of the selected creature to #entry.'),
	('npc changelevel', 8192, 'Syntax: .npc changelevel #level\r\nChange the level of the selected creature to #level. #level may range from 1 to 73.'),
	('npc delete', 8192, 'Syntax: .npc delete [#guid]\r\nDelete creature with guid #guid (or the selected if no guid is provided)'),
	('npc deleteformation', 8192, 'Syntax: .npc deleteformation\r\nDelete selected creature formation.'),
	('npc delitem', 8192, 'Syntax: .npc delitem #itemId\r\nRemove item #itemid from item list of selected vendor.'),
	('npc doaction', 8192, 'Syntax: .npc doaction #action\r\nCalls selected creature AI DoAction method.'),
	('npc enterevademode', 4096, 'Syntax: .npc enterevademode\r\nForces selected creature to evade.'),
	('npc extraflag', 8192, ''),
	('npc factionid', 8192, 'Syntax: .npc factionid #factionid\r\nSet the faction of the selected creature to #factionid.'),
	('npc fieldflag', 8192, ''),
	('npc fieldflags', 8192, 'Syntax: .npc fieldflag #fieldflag\nSet the field flags of creature template of the selected creature and selected creature to #fieldflag. flags will applied to all creatures of selected creature template after server restart or grid unload/load.'),
	('npc flag', 8192, 'Syntax: .npc flag #npcflag\r\nSet the NPC flags of creature template of the selected creature and selected creature to #npcflag. NPC flags will applied to all creatures of selected creature template after server restart or grid unload/load.'),
	('npc follow', 4096, 'Syntax: .npc follow\r\nSelected creature start follow you until death/fight/etc.'),
	('npc info', 256, 'Syntax: .npc info\r\nDisplay a list of details for the selected creature.\r\nThe list includes:\r\n- GUID, Faction, NPC flags, Entry ID, Model ID,\r\n- Level,\r\n- Health (current/maximum),\r\n- Field flags, dynamic flags, faction template,\r\n- Position information,\r\n- and the creature type, e.g. if the creature is a vendor.'),
	('npc move', 8192, 'Syntax: .npc move [#creature_guid]\r\nMove the targeted creature spawn point to your coordinates.'),
	('npc name', 8192, NULL),
	('npc playemote', 4096, 'Syntax: .npc playemote #emoteid\r\nMake the selected creature emote with an emote of id #emoteid.'),
	('npc resetai', 4096, 'Syntax: .npc resetai\r\nResets selected creature AI.'),
	('npc say', 4096, 'Syntax: .npc say $text\r\nForce selected npc to say $text.'),
	('npc setlink', 8192, 'Syntax: .npc setlink #linkguid\r\nLinks selected creature to creature with guid #linkguid.'),
	('npc setmodel', 8192, 'Syntax: .npc setmodel #displayid\r\nChange the model id of the selected creature to #displayid.'),
	('npc setmovetype', 8192, 'Syntax: .npc setmovetype [#creature_guid] stay/random/way [NODEL]\r\nSet for creature pointed by #creature_guid (or selected if #creature_guid not provided) movement type and move it to respawn position (if creature alive). Any existing waypoints for creature will be removed from the database if you do not use NODEL. If the creature is dead then movement type will applied at creature respawn.\r\nMake sure you use NODEL, if you want to keep the waypoints.'),
	('npc spawndist', 8192, 'Syntax: .npc spawndist #dist\r\nAdjust spawndistance of selected creature to dist.'),
	('npc spawntime', 8192, 'Syntax: .npc spawntime #time\r\nAdjust spawntime of selected creature to time.'),
	('npc subname', 8192, NULL),
	('npc textemote', 4096, 'Syntax: .npc textemote #emoteid\r\nMake the selected creature to do textemote with an emote of id #emoteid.'),
	('npc unfollow', 4096, 'Syntax: .npc unfollow\r\nSelected creature (non pet) stop follow you.'),
	('npc whisper', 4096, 'Syntax: .npc whisper #playerguid #text\r\nMake the selected npc whisper #text to  #playerguid.'),
	('npc yell', 4096, 'Syntax: .npc yell $text\r\nForce selected npc to yell $text.'),
	('password', 1, 'Syntax: .password $old_password $new_password $new_password\r\nChange your account password.'),
	('path', 8192, NULL),
	('path add', 8192, 'Syntax: .path add [$pathid]\r\nAdds waypoint to path'),
	('path event', 8192, 'Syntax: .path event add/mod/del/listid $id'),
	('path load', 8192, 'Syntax: .path load $id'),
	('path modify', 8192, 'Syntax: .path modify delay/action/action_chance/move_flag/del/move/wpadd'),
	('path reloadpath', 8192, 'Syntax: .path reloadpath $id\r\nReloads path given id.'),
	('path show', 8192, 'Syntax: .path show on/off/first/last/info [$guid]'),
	('path tofile', 8192, 'Syntax: .path tofile\r\nAdds current place as a waypoint for selected creature to waypoints.txt file.'),
	('path unload', 8192, 'Syntax: .path unload'),
	('pet', 4096, NULL),
	('pet create', 4096, 'Syntax: .pet create\r\nCreates a pet of the selected creature.'),
	('pet learn', 4096, 'Syntax: .pet learn\r\nLearn #spellid to pet.'),
	('pet tp', 4096, 'Syntax: .pet tp #\r\nChange pet\'s amount of training points.'),
	('pet unlearn', 4096, 'Syntax: .pet unlearn\r\nunLearn #spellid to pet.'),
	('pinfo', 2048, 'Syntax: .pinfo [$player_name] [rep]\r\nOutput account information for selected player or player find by $player_name. If "rep" parameter provided show reputation information for player.'),
	('playall', 4096, 'Syntax: .playall #soundid\r\nPlayer a sound to whole server.'),
	('plimit', 8192, 'Syntax: .plimit [#num|-1|-2|-3|reset|player|moderator|gamemaster|administrator]\r\nWithout arg show current player amount and security level limitations for login to server, with arg set player linit ($num > 0) or securiti limitation ($num < 0 or security leme name. With `reset` sets player limit to the one in the config file'),
	('possess', 4096, 'Syntax: .possess\r\nPossesses indefinitely the selected creature.'),
	('quest', 2048, NULL),
	('quest add', 2048, 'Syntax: .quest add #quest_id\r\nAdd to character quest log quest #quest_id. Quest started from item can\'t be added by this command but correct .additem call provided in command output.'),
	('quest complete', 2048, 'Syntax: .quest complete #questid\r\nMark all quest objectives as completed for target character active quest. After this target character can go and get quest reward.'),
	('quest remove', 2048, 'Syntax: .quest remove #quest_id\r\nSet quest #quest_id state to not completed and not active (and remove from active quest list) for selected player.'),
	('quest showlowlevel', 1, 'Syntax: .quest showlowlevel'),
	('recall', 2048, 'Syntax: .recall [$playername]\r\nTeleport $playername or selected player to the place where he has been before last use of a teleportation command. If no $playername is entered and no player is selected, it will teleport you.'),
	('reload', 8192, 'Syntax: .reload table_name\r\nReload table `table_name` if reload support added for this table and this table can be _safe_ reloaded.'),
	('reload access_requirement', 8192, 'Usage: .reload access_requirement\r\nReloads the access_requirement DB table.'),
	('reload all', 8192, 'Syntax: .reload all\r\nReload all tables with reload support added and that can be _safe_ reloaded.'),
	('reload all_area', 8192, 'Syntax: .reload all_area\r\nReload all `areatrigger_*` tables if reload support added for this table and this table can be _safe_ reloaded.'),
	('reload all_item', 8192, 'Syntax: .reload all_item\r\nReload PageTexts and ItemEnchantments tables.'),
	('reload all_locales', 8192, 'Syntax: .reload all_locales\r\nReload all `locales_*` tables with reload support added and that can be _safe_ reloaded.'),
	('reload all_loot', 8192, 'Syntax: .reload all_loot\r\nReload all `*_loot_template` tables. This can be slow operation with lags for server run.'),
	('reload all_npc', 8192, 'Syntax: .reload all_npc\r\nReload all npc_* tables with reload support added and that can be _safe_ reloaded.'),
	('reload all_quest', 8192, 'Syntax: .reload all_quest\r\nReload all quest related tables if reload support added for this table and this table can be _safe_ reloaded.'),
	('reload all_scripts', 8192, 'Syntax: .reload all_scripts\r\nReload all *_scripts tables with reload support added and that can be _safe_ reloaded.'),
	('reload all_spell', 8192, 'Syntax: .reload all\r\nReload all `spell_*` tables with reload support added and that can be _safe_ reloaded.'),
	('reload areatrigger_involvedrelation', 8192, 'Usage: .reload areatrigger_involvedrelation\r\nReloads the areatrigger_involvedrelation DB table.'),
	('reload areatrigger_tavern', 8192, 'Usage: .reload areatrigger_tavern\r\nReloads the areatrigger_tavern DB table.'),
	('reload areatrigger_teleport', 8192, 'Usage: .reload areatrigger_teleport\r\nReloads the areatrigger_teleport DB table.'),
	('reload auctions', 8192, 'Usage: .reload auctions\r\nReloads the auctions DB table.'),
	('reload autobroadcast', 8192, 'Usage: .reload autobroadcast\r\nReloads the autobroadcast DB table.'),
	('reload command', 8192, 'Usage: .reload command\r\nReloads the command DB table.'),
	('reload config', 8192, 'Syntax: .reload config\r\nReload config settings (by default stored in trinityd.conf). Not all settings can be change at reload: some new setting values will be ignored until restart, some values will applied with delay or only to new objects/maps, some values will explicitly rejected to change at reload.'),
	('reload creature_ai_scripts', 8192, 'Usage: .reload creature_ai_scripts\r\nReloads the creature_ai_scripts DB table.'),
	('reload creature_involvedrelation', 8192, 'Usage: .reload creature_involvedrelation\r\nReloads the creature_involvedrelation DB table.'),
	('reload creature_linked_respawn', 8192, 'Usage: .reload creature_linked_respawn\r\nReloads the creature_linked_respawn DB table.'),
	('reload creature_loot_template', 8192, 'Usage: .reload creature_loot_template\r\nReloads the creature_loot_template DB table.'),
	('reload creature_questrelation', 8192, 'Usage: .reload creature_questrelation\r\nReloads the creature_questrelation DB table.'),
	('reload disenchant_loot_template', 8192, 'Usage: .reload disenchant_loot_template\r\nReloads the disenchant_loot_template DB table.'),
	('reload eventai', 8192, 'Usage: .reload eventai\r\nReloads the eventai DB table.'),
	('reload event_scripts', 8192, 'Usage: .reload event_scripts\r\nReloads the event_scripts DB table.'),
	('reload fishing_loot_template', 8192, 'Usage: .reload fishing_loot_template\r\nReloads the fishing_loot_template DB table.'),
	('reload gameobject_involvedrelation', 8192, 'Usage: .reload gameobject_involvedrelation\r\nReloads the gameobject_involvedrelation DB table.'),
	('reload gameobject_loot_template', 8192, 'Usage: .reload gameobject_loot_template\r\nReloads the gameobject_loot_template DB table.'),
	('reload gameobject_questrelation', 8192, 'Usage: .reload gameobject_questrelation\r\nReloads the gameobject_questrelation DB table.'),
	('reload gameobject_scripts', 8192, 'Usage: .reload gameobject_scripts\r\nReloads the gameobject_scripts DB table.'),
	('reload game_graveyard_zone', 8192, 'Usage: .reload game_graveyard_zone\r\nReloads the game_graveyard_zone DB table.'),
	('reload game_tele', 8192, 'Usage: .reload game_tele\r\nReloads the game_tele DB table.'),
	('reload gm_tickets', 8192, 'Usage: .reload gm_tickets\r\nReloads GM Tickets from the database and re-caches them into memory.'),
	('reload item_enchantment_template', 8192, 'Usage: .reload item_enchantment_template\r\nReloads the item_enchantment_template DB table.'),
	('reload item_loot_template', 8192, 'Usage: .reload item_loot_template\r\nReloads the item_loot_template DB table.'),
	('reload locales_creature', 8192, 'Usage: .reload locales_creature\r\nReloads the locales_creature DB table.'),
	('reload locales_gameobject', 8192, 'Usage: .reload locales_gameobject\r\nReloads the locales_gameobject DB table.'),
	('reload locales_item', 8192, 'Usage: .reload locales_item\r\nReloads the locales_item DB table.'),
	('reload locales_npc_text', 8192, 'Usage: .reload locales_npc_text\r\nReloads the locales_npc_text DB table.'),
	('reload locales_page_text', 8192, 'Usage: .reload locales_page_text\r\nReloads the locales_page_text DB table.'),
	('reload locales_quest', 8192, 'Usage: .reload locales_quest\r\nReloads the locales_quest DB table.'),
	('reload npc_gossip', 8192, 'Usage: .reload npc_gossip\r\nReloads the npc_gossip DB table.'),
	('reload npc_option', 8192, 'Usage: .reload npc_option\r\nReloads the npc_option DB table.'),
	('reload npc_trainer', 8192, 'Usage: .reload npc_trainer\r\nReloads the npc_trainer DB table.'),
	('reload npc_vendor', 8192, 'Usage: .reload npc_vendor\r\nReloads the npc_vendor DB table.'),
	('reload page_text', 8192, 'Usage: .reload page_text\r\nReloads the page_text DB table.'),
	('reload pickpocketing_loot_template', 8192, 'Usage: .reload pickpocketing_loot_template\r\nReloads the pickpocketing_loot_template DB table.'),
	('reload prospecting_loot_template', 8192, 'Usage: .reload prospecting_loot_template\r\nReloads the prospecting_loot_template DB table.'),
	('reload quest_end_scripts', 8192, 'Usage: .reload quest_end_scripts\r\nReloads the quest_end_scripts DB table.'),
	('reload quest_mail_loot_template', 8192, 'Usage: .reload quest_mail_loot_template\r\nReloads the quest_mail_loot_template DB table.'),
	('reload quest_start_scripts', 8192, 'Usage: .reload quest_start_scripts\r\nReloads the quest_start_scripts DB table.'),
	('reload quest_template', 8192, 'Usage: .reload quest_template\r\nReloads the quest_template DB table.'),
	('reload reference_loot_template', 8192, 'Usage: .reload reference_loot_template\r\nReloads the reference_loot_template DB table.'),
	('reload reputation_reward_rate', 8192, 'Usage: .reload reputation_reward_rate\r\nReloads the reputation_reward_rate DB table.'),
	('reload reputation_spillover_template', 8192, 'Usage: .reload reputation_spillover_template\r\nReloads the reputation_spillover_template DB table.'),
	('reload reserved_name', 8192, 'Usage: .reload reserved_name\r\nReloads the reserved_name DB table.'),
	('reload skill_discovery_template', 8192, 'Usage: .reload skill_discovery_template\r\nReloads the skill_discovery_template DB table.'),
	('reload skill_extra_item_template', 8192, 'Usage: .reload skill_extra_item_template\r\nReloads the skill_extra_item_template DB table.'),
	('reload skill_fishing_base_level', 8192, 'Usage: .reload skill_fishing_base_level\r\nReloads the skill_fishing_base_level DB table.'),
	('reload skinning_loot_template', 8192, 'Usage: .reload skinning_loot_template\r\nReloads the skinning_loot_template DB table.'),
	('reload spell_affect', 8192, 'Usage: .reload spell_affect\r\nReloads the spell_affect DB table.'),
	('reload spell_disabled', 8192, 'Usage: .reload spell_disabled\r\nReloads the spell_disabled DB table.'),
	('reload spell_elixir', 8192, 'Usage: .reload spell_elixir\r\nReloads the spell_elixir DB table.'),
	('reload spell_enchant_proc_data', 8192, 'Usage: .reload spell_enchant_proc_data\r\nReloads the spell_enchant_proc_data DB table.'),
	('reload spell_pet_auras', 8192, 'Usage: .reload spell_pet_auras\r\nReloads the spell_pet_auras DB table.'),
	('reload spell_proc_event', 8192, 'Usage: .reload spell_proc_event\r\nReloads the spell_proc_event DB table.'),
	('reload spell_required', 8192, 'Usage: .reload spell_required\r\nReloads the spell_required DB table.'),
	('reload spell_scripts', 8192, 'Usage: .reload spell_scripts\r\nReloads the spell_scripts DB table.'),
	('reload spell_script_target', 8192, 'Usage: .reload spell_script_target\r\nReloads the spell_script_target DB table.'),
	('reload spell_target_position', 8192, 'Usage: .reload spell_target_position\r\nReloads the spell_target_position DB table.'),
	('reload spell_threats', 8192, 'Usage: .reload spell_threats\r\nReloads the spell_threats DB table.'),
	('reload trinity_string', 8192, 'Usage: .reload trinity_string\r\nReloads the trinity_string DB table.'),
	('reload unqueue_account', 8192, 'Usage: .reload unqueue_account\r\nReloads the unqueue_account DB table.'),
	('reload waypoint_scripts', 8192, 'Usage: .reload waypoint_scripts.\r\nReloads the waypoint_scripts DB table.'),
	('rename', 2048, NULL),
	('repairitems', 4096, 'Syntax: .repairitems\r\nRepair all selected player\'s items.'),
	('reset all', 8192, 'Syntax: .reset all spells\r\nSyntax: .reset all talents\r\nRequest reset spells or talents at next login each existed character.'),
	('reset honor', 8192, 'Syntax: .reset honor [Playername]\r\nReset all honor data for targeted character.'),
	('reset level', 8192, 'Syntax: .reset level [Playername]\r\nReset level to 1 including reset stats and talents.  Equipped items with greater level requirement can be lost.'),
	('reset spells', 8192, 'Syntax: .reset spells [Playername]\r\nRemoves all non-original spells from spellbook. Playername can be name of offline character.'),
	('reset stats', 8192, 'Syntax: .reset stats [Playername]\r\nResets(recalculate) all stats of the targeted player to their original values at current level.'),
	('reset talents', 4096, 'Syntax: .reset talents [Playername]\r\n  Removes all talents of the targeted player. Playername can be name of offline character.'),
	('respawn', 2048, 'Syntax: .respawn\r\nRespawn all nearest creatures and GO without waiting respawn time expiration.'),
	('revive', 2048, 'Syntax: .revive\r\nRevive the selected player. If no player is selected, it will revive you.'),
	('revivegroup', 2048, 'Syntax: .revivegroup\r\nRevives all players in group and teleports them to command user.'),
	('save', 256, 'Syntax: .save\r\nSaves your character.'),
	('send items', 4096, 'Syntax: .send items #playername "#subject" "#text" itemid1[:count1] itemid2[:count2] ... itemidN[:countN]\r\nSend a mail to a player. Subject and mail text must be in "". If for itemid not provided related count values then expected 1, if count > max items in stack then items will be send in required amount stacks. All stacks amount in mail limited to 12.'),
	('send mail', 2048, 'Syntax: .send mail #playername "#subject" "#text"\r\nSend a mail to a player. Subject and mail text must be in "".'),
	('send message', 2048, 'Syntax: .send message $playername $message\r\nSend screen message to player from ADMINISTRATOR.'),
	('send money', 8192, 'Syntax: .send money #playername "#subject" "#text" #money\r\nSend mail with money to a player. Subject and mail text must be in "".'),
	('server corpses', 8192, 'Syntax: .server corpses\r\nTriggering corpses expire check in world.'),
	('server exit', 8192, 'Syntax: .server exit\r\nTerminate trinity-core NOW. Exit code 0.'),
	('server idlerestart', 8192, 'Syntax: .server idlerestart #delay\r\nRestart the server after #delay seconds if no active connections are present (no players). Use #exist_code or 2 as program exist code.'),
	('server idlerestart cancel', 8192, 'Syntax: .server idlerestart cancel\r\nCancel the restart/shutdown timer if any.'),
	('server idleshutdown', 8192, 'Syntax: .server idleshutdown #delay [#exist_code]\r\nShut the server down after #delay seconds if no active connections are present (no players). Use #exist_code or 0 as program exist code.'),
	('server idleshutdown cancel', 8192, 'Syntax: .server idleshutdown cancel\r\nCancel the restart/shutdown timer if any.'),
	('server info', 1, 'Syntax: .server info\r\nDisplay server version and the number of connected players.'),
	('server motd', 8192, 'Syntax: .server motd\r\nShow server Message of the day.'),
	('server restart', 8192, 'Syntax: .server restart #delay\r\nRestart the server after #delay seconds. Use #exist_code or 2 as program exist code.'),
	('server restart cancel', 8192, 'Syntax: .server restart cancel\r\nCancel the restart/shutdown timer if any.'),
	('server rollshutdown', 8192, 'Syntax: .server rollshutdown #delay #msg\r\nShut the server down after #delay seconds and sends announce with #msg as text.'),
	('server set difftime', 8192, 'Syntax: .server set difftime #interval\r\nSet server diff time.'),
	('server set loglevel', 8192, 'Syntax: .server set loglevel #level\r\nSet server log level (0 - errors only, 1 - basic, 2 - detail, 3 - debug).'),
	('server set motd', 8192, 'Syntax: .server set motd $MOTD\r\nSet server Message of the day.'),
	('server shutdown', 8192, 'Syntax: .server shutdown #delay [#exist_code]\r\nShut the server down after #delay seconds. Use #exist_code or 0 as program exist code.'),
	('server shutdown cancel', 8192, 'Syntax: .server shutdown cancel\r\nCancel the restart/shutdown timer if any.'),
	('setskill', 4096, 'Syntax: .setskill #skill #level [#max]\r\nSet a skill of id #skill with a current skill value of #level and a maximum value of #max (or equal current maximum if not provide) for the selected character. If no character is selected, you learn the skill.'),
	('settitle', 4096, 'Syntax: .settitle $TitleID'),
	('showarea', 4096, 'Syntax: .showarea #areaid\r\nReveal the area of #areaid to the selected character. If no character is selected, reveal this area to you.'),
	('showhonor', 8192, 'Syntax: .showhonor\r\nDisplay your honor ranking.'),
	('start', 1, 'Syntax: .start\r\nTeleport you to the starting area of your character.'),
	('taxicheat', 4096, 'Syntax: .taxicheat on/off\r\nTemporary grant access or remove to all taxi routes for the selected character. If no character is selected, hide or reveal all routes to you. Visited taxi nodes sill accessible after removing access.'),
	('tele', 256, 'Syntax: .tele #location\r\nTeleport player to a given location.'),
	('tele add', 2048, 'Syntax: .tele add $name\r\nAdd current your position to .tele command target locations list with name $name.'),
	('tele del', 4096, 'Syntax: .tele del $name\r\nRemove location with name $name for .tele command locations list.'),
	('tele group', 2048, 'Syntax: .tele group#location\r\nTeleport a selected player and his group members to a given location.'),
	('tele name', 2048, 'Syntax: .tele name #playername #location\r\nTeleport a player to a given location.'),
	('ticket assign', 256, 'Syntax: .ticket assign $ticketid $gmname.\r\nAssigns the specified ticket to the specified Game Master.'),
	('ticket close', 256, 'Syntax: .ticket close $ticketid.\r\nCloses the specified ticket. Does not delete permanently.'),
	('ticket closedlist', 256, 'Syntax: .ticket closedlist\r\nDisplays a list of closed GM tickets.'),
	('ticket comment', 256, 'Syntax: .ticket comment $ticketid $comment.\r\nAllows the adding or modifying of a comment to the specified ticket.'),
	('ticket delete', 8192, 'Syntax: .ticket delete $ticketid.\r\nDeletes the specified ticket permanently. Ticket must be closed first.'),
	('ticket list', 256, 'Syntax: .ticket list\r\nDisplays a list of open GM tickets.'),
	('ticket onlinelist', 256, 'Syntax: .ticket onlinelist\r\nDisplays a list of open GM tickets whose owner is online.'),
	('ticket response', 256, 'Syntax: .ticket response #id #msg\r\nSends mail to player who opens ticket with id #id and closes this ticket.'),
	('ticket unassign', 256, 'Usage: .ticket unassign $ticketid.\r\nUnassigns the specified ticket from the current assigned Game Master.'),
	('ticket viewid', 256, 'Usage: .ticket viewid $ticketid.\r\nReturns details about specified ticket. Ticket must be open and not deleted.'),
	('ticket viewname', 256, 'Usage: .ticket viewname $creatorname.\r\nReturns details about specified ticket. Ticket must be open and not deleted.'),
	('unaura', 4096, 'Syntax: .unaura #spellid\r\nRemove aura due to spell #spellid from the selected Unit.'),
	('unban account', 2048, 'Syntax is: unban account $Name\r\nUnban accounts for account name pattern.'),
	('unban character', 2048, 'Syntax is: unban character $Name\r\nUnban accounts for character name pattern.'),
	('unban email', 2048, 'Syntax: .unban email $email\r\nUnbans email address for $email pattern'),
	('unban ip', 2048, 'Syntax is: unban ip $Ip\r\nUnban accounts for IP pattern.'),
	('unbindfollow', 256, 'Syntax: .unbindfollow\r\nRemoves follow binding.'),
	('unbindsight', 256, 'Syntax: .unbindsight\r\nRemoves bound vision. Cannot be used while currently possessing a target.'),
	('unfreeze', 256, 'Syntax: .unfreeze (#player)\r\n"Unfreezes" #player and enables his chat again. When using this without #name it will unfreeze your target.'),
	('unlearn', 4096, 'Syntax: .unlearn #startspell #endspell\r\nUnlearn for selected player the range of spells between id #startspell and #endspell. If no #endspell is provided, just unlearn spell of id #startspell.'),
	('unmute', 2048, 'Syntax: .unmute $playerName\r\nRestore chat messaging for any character from account of character $playerName.'),
	('unpossess', 256, 'Syntax: .unpossess\r\nIf you are possessed, unpossesses yourself; otherwise unpossesses current possessed target.'),
	('vipadd', 8192, 'Syntax: .vipadd $account_id $5d2h10m15s\r\n\r\nAdd a vip account with time to expire.'),
	('vipdel', 8192, 'Syntax: .vipdel $account_id\r\n\r\nDelete a vip account.'),
	('waterwalk', 2048, 'Syntax: .waterwalk on/off\r\nSet on/off waterwalk state for selected player or self if no player selected.'),
	('wchange', 8192, 'Syntax: .wchange #weathertype #status\r\nSet current weather to #weathertype with an intensity of #status. #weathertype can be 1 for rain, 2 for snow, and 3 for sand. #status can be 0 for disabled, and 1 for enabled.'),
	('weather', 2048, 'Syntax: .weather on/off\r\nEnable/Disable weather changing for account.'),
	('whispers', 256, 'Syntax: .whispers on|off\r\nEnable/disable accepting whispers by GM from players. By default use trinityd.conf setting.'),
	('wp', 8192, NULL),
	('wp add', 8192, 'Syntax: .wp add [$pathid]\r\nAdds waypoint to path'),
	('wp event', 8192, 'Syntax: .wp event add/mod/del/listid $id'),
	('wp load', 8192, 'Syntax: .wp load $id'),
	('wp modify', 8192, 'Syntax: .wp modify delay/action/action_chance/move_flag/del/move/wpadd'),
	('wp reloadpath', 8192, 'Syntax: .wp reloadpath $id\r\nReloads path given id.'),
	('wp show', 8192, 'Syntax: .wp show on/off/first/last/info [$guid]'),
	('wp tofile', 8192, 'Syntax: .wp tofile\r\nAdds current place as a waypoint for selected creature to waypoints.txt file.'),
	('wp unload', 8192, 'Syntax: .wp unload');
/*!40000 ALTER TABLE `command` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
